fix:Update Total daily batta field when Batta field is changed.
efeone/beams pull request #131
Opened 2024-09-10 11:32 UTC by ZakkiyathLulu

## Fix:
Update  Total daily batta field when  Batta field is changed.

## Solution description
 Total Daily Batta is calculated based on days and Batta  and updated when either one is changed.

## Output
![image](https://github.com/user-attachments/assets/7eaa3607-da52-4013-9cdc-e70aba46b1eb)

## Is there any existing behavior change of other features due to this code change?
-No

## Was this feature tested on the browsers?
  - Mozilla Firefox

2024-09-10 11:37 UTC, SherinKR submitted a review, later dismissed

2024-09-10 11:37 UTC, SherinKR commented on beams/beams/doctype/batta_claim/batta_claim.json
> -  "purpose",
Why purpose is deleted?

2024-09-11 05:48 UTC, MhmdSinanKT requested changes
Ensure the calculation is happening when Work Detail table data is modified

2024-09-11 05:48 UTC, MhmdSinanKT commented on beams/beams/doctype/batta_claim/batta_claim.js
> -
don't remove this

2024-09-11 07:51 UTC, merged