feat : Add item filter and total amount calculation for Contract and …
efeone/beams pull request #168
Opened 2024-09-23 04:35 UTC by Nidhashirinniyas

## Feature Description
- Create child table Services
- Add filter to the item
- Fetch total amount 

## Solution Description
- Add child table to contract
- Added filter to item (main stock = 0)
- Total amount is generated by adding amount of child table

##Output
[Screencast from 23-09-24 10:02:24 AM IST.webm](https://github.com/user-attachments/assets/b2e6a87b-b018-41b7-89d5-e6b6abfccd99)

2024-09-23 05:59 UTC, SherinKR requested changes

2024-09-23 05:59 UTC, SherinKR commented on beams/beams/doctype/services/services.json
> +   "options": "Item"
It should be "Item"

2024-09-23 05:59 UTC, SherinKR commented on beams/public/js/contract.js
> +}
Calling this method in refresh and onload without any condition checking will cause to always dirty form

2024-09-23 06:54 UTC, SherinKR requested changes

2024-09-23 06:54 UTC, SherinKR commented on beams/beams/doctype/services/services.json
> +   "fieldname": "items",
why items in field_name?

2024-09-24 06:10 UTC, MhmdSinanKT approved these changes

2024-09-24 06:10 UTC, merged