feat: Set overdue status for Local Enquiry Reports
efeone/beams pull request #276
Opened 2024-10-30 08:08 UTC by anjusha12

## Is this a Feature, Chore or Bug?
- Feat

## Clearly and concisely describe the feature, chore or bug.
- Update Local Enquiry Report status to 'Overdue' when enquiry completion date exceeds expected completion date.

## Solution description
- Added functionality to update the status of Local Enquiry Report records to 'Overdue' based on the enquiry completion date and expected completion date.

## Areas affected and ensured
- Local Enquiry Report

## Is there any existing behavior change of other features due to this code change?
No

## Did you test with the following dataset?
Existing Data
New Data

2024-10-30 08:13 UTC, MhmdSinanKT requested changes

2024-10-30 08:13 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        for enquiry in enquiries:
use either double quotes or single, not both

2024-10-30 08:13 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +            if not doc.enquiry_completion_date or getdate(doc.enquiry_completion_date) > getdate(doc.expected_completion_date):
use the already fetched values at line 24 for this condition check

2024-10-30 08:13 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report_list.js
not mentioned in the PR

2024-11-01 05:26 UTC, SherinKR approved these changes

2024-11-01 05:26 UTC, merged