feat:Updated Local Enquiry Report
efeone/beams pull request #306
Opened 2024-11-06 08:24 UTC by ZakkiyathLulu

##Feature Overview
Assignment of Enquiry Officer: Added a validation to ensure that an enquiry officer is selected before progressing the workflow to "Assign to Enquiry Officer" state.
Manager Role Validation: Ensured that only managers can transition the workflow from "Draft" to "Assign to Enquiry Officer."
Start and Completion Date Automation: Automatically sets the start and  completion date based on workflow states.
Automated Workflow and Status Updates:

Workflow restrictions allow only authorized users (e.g., HR manager,Enquiry Manager and Enquiry officer) to transition certain states.

## Solution Summary
Modified workflow states:State Transitions:
Draft->Assign to Admin->Assigned to Admin(HR Manager)
Assigned to Admin->Assign to Enquiry Officer->Assigned to Enquiry Officer(Enquiry Manager)--->
Assigned to Enquiry Officer->Start Enquiry->Enquiry on Progress(Enquiry Officer)------------->
Enquiry on Progress->Enquiry Completed->Pending Approval(Enquiry Officer)
Assigned to Enquiry Officer->Enquiry Completed->Pending Approval(Enquiry Officer)
Pending Approval->Approve->Approved(HR Manager)
Pending Approval->Reject->Rejected(HR Manager)

Added validation logic in validate() function of Local Enquiry Report doctype to check the selection of an enquiry officer.

The Local Enquiry Report document is assigned for Enquiry manger from draft state and He the reassigns it to Enquiry Officer.
Automated Date Management: Set Enquiry Start and Completion dates automatically when  corresponding workflow states  are triggered(Start Enquiry  and enquiry Completed).

## Files Affected
beams/beams/custom_scripts/local_enquiry_report/local_enquiry_report.py

##Screenshots
![image](https://github.com/user-attachments/assets/03d21f45-262b-4ec5-9204-16b223b5c0b5)
![image](https://github.com/user-attachments/assets/de816e07-a9ac-4a8c-8f1c-fc7551c55428)![image](https://github.
![image](https://github.com/user-attachments/assets/f3c75947-b6dc-4696-8d1c-8eda4dffef51)
![image](https://github.com/user-attachments/assets/1fdedd17-9145-4422-b5d1-f1875925ffe1)
![image](https://github.com/user-attachments/assets/2aad3b6f-522f-4af1-814f-9a6864a4b3ed)(since condition given in workflow the action button will show only if the field enquiry officer is selected)
![image](https://github.com/user-attachments/assets/2e2fea51-ca9b-4649-87e7-4aa5dde75970)
![image](https://github.com/user-attachments/assets/0a704c06-a016-403e-aa9f-8c96e3e5ef6b)
![image](https://github.com/user-attachments/assets/b90dd69e-8c74-45f3-b9e4-cc18e8fea9e7)
![image](https://github.com/user-attachments/assets/5729ec32-2276-4e53-b35d-e6f79a2e437a)
![image](https://github.com/user-attachments/assets/8bb87315-7006-4925-9cf0-dfef2038e0da)
![image](https://github.com/user-attachments/assets/7921207a-bd0c-44f4-b5e8-e48ce4f800b0)
![image](https://github.com/user-attachments/assets/41a5bb99-7423-4965-8561-ff995dc27939)(start date populated (read only ))
![image](https://github.com/user-attachments/assets/f978f9d0-923c-4ae9-b93a-d907466ed801)(completion date set)
![image](https://github.com/user-attachments/assets/ab7a0645-3920-4473-ad10-d33e243115b8)
![Uploading image.png…]()

## Testing and Dataset

Tested with Existing Data: Verified workflow and automated status changes on existing reports.
Tested with New Data: Created new reports to ensure correct assignment and validation of officers and managers.

## Behavior Changes
 No other features affected by this change.

## Patch Required
       No

## Was this feature tested on the browsers?
  - Chrome
  - Mozilla Firefox

2024-11-06 10:30 UTC, MhmdSinanKT requested changes

2024-11-06 10:30 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.js
> +// Copyright (c) 2022, Frappe Technologies Pvt. Ltd. and contributors
don't change this

2024-11-06 10:30 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +                frappe.db.commit()  # Commit the changes to the database
is this necessary?

2024-11-06 10:30 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +
not required

2024-11-06 10:30 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        frappe.msgprint(_("Enquiry Manager  has been Assigned."))
remove double space

2024-11-06 10:30 UTC, MhmdSinanKT commented on beams/hooks.py
> +        }
unnecessary changes

2024-11-06 11:40 UTC, MhmdSinanKT requested changes

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.js
> +      }
use set only once setting in doctype

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +# Copyright (c) 2022, Frappe Technologies Pvt. Ltd. and contributors
undo this

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        self.information_required()  # Assuming you need to call this once
unnecessary comment

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +                frappe.db.set_value("Local Enquiry Report", self.name, "enquiry_officer", self.enquiry_officer)
What is this line supposed to do? this line is simmply setting the same value in the same field

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +                    frappe.db.set_value("Local Enquiry Report", self.name, "enquiry_officer", self.enquiry_officer)
What is this line supposed to do? this line is simmply setting the same value in the same field

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/public/js/job_applicant.js
> +          }
do this in python, client side validations should be reactive

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/public/js/job_requisition.js
> +              "btn-secondary"  // Set as a secondary button
is this necessary?

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/public/js/job_requisition.js
> +              "btn-secondary"  // Set as a secondary button
is this necessary?

2024-11-06 11:40 UTC, MhmdSinanKT commented on beams/public/js/job_requisition.js
> +              dropdownActions.text("Create");
use snake_case

2024-11-07 03:57 UTC, SherinKR requested changes

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        if self.workflow_state == 'Assigned to Admin':
Check the workflow_sate condition with in line documentation

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +                doc = frappe.get_doc('Local Enquiry Report', doc)
Why this is required?

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        manager_id = managers[0].parent
User default frappe methods to get user with role

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +            doc = frappe.get_doc("Local Enquiry Report", doc)
Why this is required?

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        )
Use builtin method to get assignments and Close

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        doc.save(ignore_permissions=True)
Is this tested properly? Why doc.save() is required on workflow actions?

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        doc.save(ignore_permissions=True)
Is this tested properly? Why doc.save() is required on workflow actions?

2024-11-07 03:57 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        as_list=True
Please restructure the Query in a readable format

2024-11-07 08:08 UTC, SherinKR requested changes

2024-11-07 08:08 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        if self.workflow_state == 'Assign to Enquiry Officer':
Is workflow_state name is correct?

2024-11-07 08:08 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
>              missing_fields = []
Why missing_fields is used?

2024-11-07 08:08 UTC, SherinKR commented on beams/beams/doctype/local_enquiry_report/local_enquiry_report.py
> +        user_id = frappe.db.get_value("Employee", {"name": doc.enquiry_officer}, "user_id")
Check existence of the document before using get_value

2024-11-07 12:21 UTC, merged