feat: Workflow for Customer Approval & Account Approval
efeone/beams pull request #32
Opened 2024-08-17 04:48 UTC by anjusha12

## Is this a Feature, Chore or Bug?
- Feature

## Clearly and concisely describe the feature, chore or bug.
- A new account is disabled by default and needed an approval workflow to be enabled. It will only be enabled once approved.
- A new customer is disabled by default and needed an approval workflow to be enabled. It will only be enabled once approved.

## Solution description 
- Created workflow for Customer Approval and account Approval 

## Output screenshots(optional)
[Screencast from 08-17-2024 10:07:05 AM.webm](https://github.com/user-attachments/assets/511387d9-2c6d-49ef-950c-8724fb9931a6)
[Screencast from 08-17-2024 10:05:24 AM.webm](https://github.com/user-attachments/assets/059124ca-bbfc-4a97-a165-6f80d2bf7b78)

## Areas affected and ensured
-`beams/hooks.py`
-`beams/fixtures/`
-`beams/public/js/account.js`
-`beams/public/js/customer.js`

## Did you test with the following dataset?
- Existing Data
- New Data

2024-08-17 04:55 UTC, MhmdSinanKT requested changes
If both customer and account are disabled by default, then the value of the disable checkbox should be 1 on creation. Use field default in doctype instead of client script. Similarly, use server script to update the value of checkbox.

2024-08-17 05:03 UTC, MhmdSinanKT commented on beams/fixtures/role.json
> +]
Why is this in fixture? it is already present in ERPNext

2024-08-17 06:08 UTC, MhmdSinanKT commented on beams/hooks.py
> +    "Customer": "public/js/customer.js",
remove these lines if there are no corresponding files

2024-08-17 06:34 UTC, MhmdSinanKT approved these changes

2024-08-17 06:37 UTC, MhmdSinanKT requested changes
Change custom fields to work on setup

2024-08-19 06:41 UTC, SherinKR approved these changes

2024-08-19 06:41 UTC, merged