feat:Created doctype Employee Exit Clearance and child table Employee Clearance.
efeone/beams pull request #439
Opened 2024-12-16 06:31 UTC by ZakkiyathLulu

## Feature description
Create  doctype  Employee Exit Clearance and child table Employee Clearance.

## Analysis and design (optional)
Create  doctype  Employee Exit Clearance with following fields:

- Role Permission-HR Manager,HOD
- It should be Submittable doctype
- Employee(Link,option-Employee,mandatory)
- Employee Name(Read-only,fetch from employee)
- Department(link to Department,fetch from employee)
- Designation(link to designation,fetch from employee)
- Employee Separation Begins on(Date)
- Relieving Date(Date,fetch from employee)
- Notice Period(Int,fetch from employee)
- Pending Dues(check)
- Amount(float,show this field only if Pending Dues is checked)

Create childtable  Employee Clearance :
-Department(link,option-department)
- Employee Exit Clearance(link,option-Employee Exit Clearance)
- Status(select,options-pending,completed)-----set status to completed when the Employee Exit Clearance is submitted

## Solution description
Created doctype  Employee Exit Clearance with above mentioned fields and permissions set to HOD and HR Manager.

## Output screenshots (optional)

![image](https://github.com/user-attachments/assets/be4ca58f-9c11-4cb9-be8c-4a08754d989c)
![Uploading image.png…]()

## Areas affected and ensured
Employee Exit  Clearance
Employee  Clearance 

## Is there any existing behavior change of other features due to this code change?
 No. 

## Was this feature tested on the browsers?
  - Chrome
  - Mozilla Firefox

2024-12-16 07:55 UTC, SherinKR requested changes

2024-12-16 07:55 UTC, SherinKR commented on beams/beams/doctype/employee_clearance/employee_clearance.json
> +  }
Bring status to right. Is \n required in option

2024-12-16 07:55 UTC, SherinKR commented on beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.json
> +  },
Department should be Link

2024-12-16 07:55 UTC, SherinKR commented on beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.json
> +  },
Designation should be Link

2024-12-16 07:55 UTC, SherinKR commented on beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.json
> +  },
It should be Currency

2024-12-16 11:27 UTC, SherinKR requested changes

2024-12-16 11:27 UTC, SherinKR commented on beams/beams/doctype/employee_exit_clearance/employee_exit_clearance.json
> +   "fieldtype": "Data",
Change to Date

2024-12-17 10:54 UTC, SherinKR approved these changes

2024-12-17 10:54 UTC, MhmdSinanKT approved these changes

2024-12-17 10:54 UTC, merged