feat: Create DocType Release Order
efeone/beams pull request #8
Opened 2024-08-05 11:18 UTC by anjusha12

## Clearly and concisely describe the feature, chore or bug.
- a DocType Release Order is needed which is similar to Sales Order DocType.

## Solution description
- Created DocType Release Order.

## Output screenshots (optional)
![image](https://github.com/user-attachments/assets/20b87948-0e5c-4f4e-bc8f-2bd05fab8111)
![image](https://github.com/user-attachments/assets/314b605d-678b-4515-a540-67169a78731b)
![image](https://github.com/user-attachments/assets/d1597586-0280-4801-938e-d1755f94a99f)
![image](https://github.com/user-attachments/assets/f4da7a9a-12f2-4591-87b0-082e94d1f1ca)

## Areas affected and ensured
-`beams/beams/doctype/`

## Is there any existing behavior change of other features due to this code change?
- No

2024-08-05 11:28 UTC, MhmdSinanKT approved these changes

2024-08-06 04:17 UTC, SherinKR requested changes

2024-08-06 04:17 UTC, SherinKR commented on beams/beams/doctype/release_order/release_order.json
> +   "options": "Release Order Item",
@anjusha12 @MhmdSinanKT not able to find Release Order Item doctype files.

2024-08-06 04:17 UTC, SherinKR commented on beams/beams/doctype/release_order/release_order.json
> +   "options": "SAL-ORD-.YYYY.-",
@anjusha12 Change naming series with respect Release Order

2024-08-07 03:53 UTC, merged